# Generated by Django 3.2.7 on 2021-11-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_cleanspotuser_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanspotuser',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='cleanspotuser',
            name='name_display_site',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя отображения на сайте'),
        ),
    ]
