# Generated by Django 3.2.8 on 2021-12-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_alter_servicetype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.CharField(blank=True, max_length=128, verbose_name='Описание типа пользователя'),
        ),
    ]
