# Generated by Django 3.2.8 on 2021-12-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0007_servicetype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='basic_service',
            field=models.BooleanField(default=False, verbose_name='Основная услуга'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='user_type_for_service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_for_service_types', to='cartapp.usertypeforservicetype', verbose_name='Тип пользователя для типа услуг'),
        ),
    ]
