# Generated by Django 3.2.8 on 2021-12-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0008_auto_20211203_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartservice',
            name='session_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ключ сессии'),
        ),
    ]
