# Generated by Django 3.2.8 on 2021-12-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0009_cartservice_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='services',
        ),
        migrations.AddField(
            model_name='cart',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_cart', to='cartapp.cartservice', verbose_name='Услуга для корзины'),
        ),
    ]
