# Generated by Django 3.2.8 on 2021-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0010_auto_20211206_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cleaning_days',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
