# Generated by Django 3.2.8 on 2021-12-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0014_auto_20211207_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cleaning_days',
        ),
        migrations.AddField(
            model_name='cart',
            name='cleaning_days',
            field=models.ManyToManyField(blank=True, null=True, to='cartapp.DaysOfWeek', verbose_name='День недели'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='services',
        ),
        migrations.AddField(
            model_name='cart',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_cart', to='cartapp.CartService', verbose_name='Услуга для корзины'),
        ),
    ]
