# Generated by Django 3.2.8 on 2021-12-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0015_auto_20211207_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cleaning_days',
        ),
        migrations.AddField(
            model_name='cart',
            name='cleaning_days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartapp.daysofweek', verbose_name='День недели'),
        ),
    ]
