# Generated by Django 3.2.8 on 2021-12-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0020_alter_cart_cleaning_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cleaning_days',
            field=models.ManyToManyField(blank=True, to='cartapp.DaysOfWeek', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='cartapp.CartService', verbose_name='Услуга для корзины'),
        ),
    ]
