# Generated by Django 3.2.8 on 2021-12-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0021_auto_20211208_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowWashing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_windows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество окон')),
                ('num_window_frame', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество створок окон')),
                ('num_stained_windows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество витражных окон')),
                ('num_stained_window_frame', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество створок витражных окон')),
                ('num_showcase', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество витрин')),
                ('square_windows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь остекления окон')),
                ('square_showcase', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь остекления витрин')),
                ('height_showcase', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота витрин')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='windows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartapp.windowwashing', verbose_name='Окна'),
        ),
    ]
