# Generated by Django 3.2.8 on 2021-12-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0022_auto_20211209_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_windows',
            field=models.BooleanField(default=False),
        ),
    ]
