# Generated by Django 3.2.8 on 2021-12-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0025_auto_20211209_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_order',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения заказа'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_other_date',
            field=models.BooleanField(default=False, verbose_name='Готов рассмотреть другие даты уборки'),
        ),
    ]
