# Generated by Django 3.2.8 on 2021-11-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('orderapp', '0002_auto_20211124_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='premise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.premises', verbose_name='Помещение'),
        ),
    ]
