# Generated by Django 3.2.8 on 2021-12-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
