# Generated by Django 3.2.8 on 2021-12-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('orderapp', '0007_order_is_other_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='premise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.premises', verbose_name='Помещение'),
        ),
    ]
