# Generated by Django 3.2.8 on 2021-12-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_alter_order_premise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_other_date',
        ),
    ]
