# Generated by Django 3.2.7 on 2021-11-07 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremisesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Тип помещения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещений',
            },
        ),
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premises_street', models.CharField(max_length=128, verbose_name='Улица')),
                ('premises_house_num', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('premises_apartment', models.CharField(blank=True, max_length=10, verbose_name='Квартира')),
                ('premises_intercom', models.CharField(blank=True, max_length=5, verbose_name='Домофон')),
                ('premises_entrance', models.CharField(blank=True, max_length=2, verbose_name='Подъезд')),
                ('premises_floor', models.CharField(blank=True, max_length=3, verbose_name='Этаж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('premises_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.cities', verbose_name='Город')),
                ('premises_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец помещения')),
                ('premises_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.premisestype', verbose_name='Тип помещения')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
    ]
